### PR TITLE
reflect published gem

### PR DESCRIPTION
**Pull request by szhu**
See also: IFTTT/kramdown-tablerize#2

### CODE REVIEW

**Comment by devinfoley** [comment]
:tada:

**Comment by szhu** [comment]
Thanks @devinfoley! Before you merge, let me know if I can add build status badges to the READMEs.

**Comment by szhu** [comment]
Oh, I need a `Gemfile` to make rspec work. I'll do that.

**Comment by szhu** [comment]
Ready for merge.

**Comment by devinfoley** [comment]
@szhu feel free to merge these yourself! Don't let me slow you down!

**Comment by szhu** [comment]
I think I have only read-only access though

**Comment by devinfoley** [comment]
Check your inbox!

**Comment by szhu** [comment]
thanks! merging.

**Pull request merged**
